### ISSUE TITLE
App Size Discussion

### ISSUE THREAD

**Issue by n-ce** [belelaritra/Neumorphic_Calculator#7]
16 MB for a calculator sounds too unhealthy, don't ya think?
I'm pretty sure this is because of flutter which increases any app's size to 5 times.
I think basic apps like this must be coded in Java for superfast performance.
For reference : The latest Google Calculator costs 2.8MB.

**Comment by danger-ahead** [comment]
Hi @n-ce 

This project uses flutter. And flutter is a heavy UI template meant for heavy apps that's otherwise difficult to do in native tech.
We would like to term this more as an "enthusiast" project.

> For reference : The latest Google Calculator costs 2.8MB
This can be achieved by splitting the apk (according to the different architectures). You can find the split apks in the GitHub Release. To know which architecture your cpu is, kindly google and install the correct apk accordingly. The split apks are in between 5-6MB.

Closing this. Let me know if I can help you with anything else, or if you would like this issue to be reopened.
